### ISSUE TITLE
Study room availability scraper

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/peterportal-api-next#39]
Notes:
![image](https://github.com/icssc/peterportal-api-next/assets/89349085/6f7f332b-d700-488c-815e-1c83ff6ca6d4)
https://www.lib.uci.edu/sites/all/scripts/occuspace.php?id=666

**Comment by ecxyzzy** [comment]
Going to icebox this since ZotMeet is on hold at the moment.

**Comment by cokwong** [comment]
@sanskarm7 Try creating a function to grab all unique room IDs by making a POST request to https://spaces.lib.uci.edu/spaces/availability/grid

example:
```
curl --location 'https://spaces.lib.uci.edu/spaces/availability/grid' \
--header 'Referer: https://spaces.lib.uci.edu/spaces?lid=6579' \
--form 'lid="6579"' \
--form 'gid="0"' \
--form 'start="2024-01-22"' \
--form 'end="2024-01-23
"' \
--form 'pageSize="18"'
