### ISSUE TITLE
RFC: Constructs as Configuration

### ISSUE THREAD

**Issue by ap0nia** [icssc/peterportal-api-next#62]
# Introduction
### Current Strategy for Configuration
It's very vanilla and basically uses a JSON schema to declaratively describe how the app should work. e.g. like `Vite` and their `defineConfig` convention.

### Issues
This works fine within our limited scope of creating a backend API because we have a defined stack with specific constructs, overrides, etc. However, I'm interested in expanding the scope to be more application agnostic, with support for static sites and server-side rendered sites. Basically, like [SST](https://sst.dev/) but with less overhead.

### Premise
No matter what we do, or cloud provisioning provider we use, we'll inevitably end up back at [Constructs](https://github.com/aws/constructs), e.g. CDK and CDKTF to define our infrastructure and application. It seems infeasible to predict all the possible settings for all possible constructs in a declarative configuration file. For example, maybe you'd need an "api" key with configuration overrides for the `Api` construct, and "api-routes" key for the `ApiRoute`, "static" for static sites, etc. On the other hand, the constructs themselves already know what props they need, and how they'll use them.

# Proposal
All ant-stack configuration files will be based off constructs.
- The root configuration file needs to export default a function that will initialize the stacks and constructs, then returns the app
- Any sub-projects that need to override settings initialized at the root will export a class that extends the relevant override construct

## How it works, i.e. the Api construct
- At the root, a new app is created with the stack that contains our custom Api construct
- When starting the dev server, building the api routes, etc. we'll look for stacks in `app.node.children`, and then look for the special Api construct in the `stacks.node.children`
- The Api construct contains a record of full paths to API routes on disk mapped to their `ApiRoute` constructs, which each contain a `config` property
  - during initialization, the Api construct populated this record with directory-based routing
- We can read from this record to determine nested configs/overrides
- Special constructs will both have a static and instance variable `type`
   - This type allows us to filter instantiated constructs as well as uninstantiated ones
   - Any construct that's created within another construct will be initialized and have the instance property, which can be filtered from node children
   - But any override constructs will not be, i.e. here: https://github.com/icssc/peterportal-api-next/blob/cdk-cicd/apps/api/v1/rest/calendar/ant.config.ts
   - This class is not initialized, but inherits the static property `type` from its parent, so during runtime, we can check all of the exported properties from the `ant.config.ts` module, and invoke `ApiRouteConfigOverride.isApiRouteConfigOverride` that reads this `type` property to confirm that we should initialize this class within the scope of another construct
   - We prefer __not__ to initialize the class if we don't have to, since it will automatically append itself to the parent node's children and then become part of the construct tree; this seems like the most reasonable way to predict whether or not the class is appropriate to be initialized before initializing it --> using a static `type` property

# Pros
- We define the application's infrastructure once, and it'll work during the AWS `cdk` CLI tool, as well as within our internal tooling with building, development server, etc.
- We don't have to predict all the possible settings to encompass in a single configuration object; each part of the app can define its constructs as needed. The difficult part is just writing everything so it's supported

# Cons
- It's imperative and less succinct

**Comment by ecxyzzy** [comment]
This makes a lot of sense. Some quick questions:

* The developer experience will remain (close to) the same for contributors wishing to creating a new endpoint, correct? The original DX intent for migrating over was that the process would be as easy as creating a new project under `/apps/api/v1/rest/`.
* How exactly do you plan on supporting per-route CDK settings (i.e. for the websoc route, which requires Lambda invoke permissions)?

**Comment by ecxyzzy** [comment]
Sounds good—can you give an estimation of how much effort this will require on your (and/or my) part?

**Comment by ap0nia** [comment]
Right now, I have a minimally working implementation. 

The next big obstacle to address is how to organize different interactions with these constructs. For example, the `Api` construct won't have the same development server logic or build logic as `SsrSite`.

I think I can get this finished over the weekend along with my CI/CD branch (sorry, multiple features in one branch).

The end goal is that we would have a valid CDK app in the root `ant.config.ts`, that can be invoked directly by the `cdk` CLI and also by our internal tooling for development, building, etc. that can support more than just a backend API (coming soon :tm:)

**Comment by ecxyzzy** [comment]
Sounds good, thanks for working on this!

> sorry, multiple features in one branch

No worries, `ant-stack` has kind of been vaguely defined in terms of features so I'm fine letting it creep a little bit.

**Comment by ap0nia** [comment]
Will be closing since I got comments. :rocket:

Actual package release definitely coming soon :tm:
