### ISSUE TITLE
Sandbox doesn't take up viewport

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/peterportal-api-next#84]
The sandbox iframe doesn't take up the whole viewport. It works when I force its height to be 100vh in inspect element.

![image](https://github.com/icssc/peterportal-api-next/assets/64875104/d4470e12-4c9f-46ea-81ce-438bc9dbfa27)

**Comment by ap0nia** [comment]
Ok cool, it wasn't just me. I don't think this is our fault though; we're using the vanilla GraphQL sandbox plugin :shrug:
